import { Container, Header, Sidebar } from '../../components'

export function Disclaimer() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <div className="flex">
        <Sidebar />
        <Container className="flex-1">
          <div className="max-w-4xl mx-auto py-8">
            <h1 className="text-4xl font-bold text-foreground mb-8">Disclaimer</h1>
            
            <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">1. General Disclaimer</h2>
                <p className="text-muted-foreground">
                  The information provided by Kair0s ("we," "us," or "our") on our AI Gateway service is for general informational purposes only. All information on the service is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">2. AI Model Outputs</h2>
                <p className="text-muted-foreground mb-4">
                  Our AI Gateway provides access to various artificial intelligence models. Please be aware that:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2">
                  <li>AI model outputs are generated by machine learning algorithms and may contain errors, inaccuracies, or biases</li>
                  <li>We do not guarantee the accuracy, reliability, or appropriateness of AI-generated content</li>
                  <li>AI models may produce content that is offensive, harmful, or inappropriate</li>
                  <li>Users are responsible for verifying and validating AI-generated information</li>
                  <li>AI models do not possess human understanding, consciousness, or intent</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">3. Professional Advice</h2>
                <p className="text-muted-foreground">
                  The information provided through our service does not constitute professional advice, whether medical, legal, financial, or otherwise. Always seek the advice of qualified professionals with any questions you may have regarding a specific situation. Do not disregard professional advice or delay in seeking it because of something you have read or received through our service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">4. Service Availability</h2>
                <p className="text-muted-foreground mb-4">
                  We strive to maintain high service availability, but please note that:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2">
                  <li>The service may be temporarily unavailable due to maintenance, technical issues, or other factors</li>
                  <li>We do not guarantee uninterrupted or error-free service</li>
                  <li>Third-party AI model providers may experience outages affecting our service</li>
                  <li>We are not liable for any damages resulting from service unavailability</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">5. External Links</h2>
                <p className="text-muted-foreground">
                  Our service may contain links to external websites that are not provided or maintained by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">6. Limitation of Liability</h2>
                <p className="text-muted-foreground mb-4">
                  In no event shall Kair0s, its directors, employees, partners, agents, suppliers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2">
                  <li>Your use of the service</li>
                  <li>AI-generated content or recommendations</li>
                  <li>Service interruptions or outages</li>
                  <li>Unauthorized access to or alteration of your transmissions or data</li>
                  <li>Statements or conduct of any third parties on the service</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">7. User Responsibility</h2>
                <p className="text-muted-foreground mb-4">
                  Users are responsible for:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2">
                  <li>Verifying the accuracy and appropriateness of AI-generated content</li>
                  <li>Using the service in a lawful and ethical manner</li>
                  <li>Protecting their own data and privacy</li>
                  <li>Complying with all applicable laws and regulations</li>
                  <li>Not relying solely on AI outputs for critical decisions</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">8. Intellectual Property</h2>
                <p className="text-muted-foreground">
                  While we strive to respect intellectual property rights, AI models may inadvertently generate content that resembles existing copyrighted material. Users are responsible for ensuring their use of AI-generated content does not infringe on third-party intellectual property rights.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">9. No Warranty</h2>
                <p className="text-muted-foreground">
                  The service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no representations or warranties of any kind, express or implied, as to the operation of the service or the information, content, materials, or products included on this service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">10. Indemnification</h2>
                <p className="text-muted-foreground">
                  You agree to indemnify and hold harmless Kair0s and its affiliates from and against any and all claims, liabilities, damages, losses, and expenses, including reasonable attorney's fees, arising from or in any way related to your use of the service or violation of these terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">11. Modifications</h2>
                <p className="text-muted-foreground">
                  We reserve the right to modify this disclaimer at any time. Any changes will be effective immediately upon posting to this page. Your continued use of the service constitutes acceptance of these modifications.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-foreground mb-4">12. Contact Information</h2>
                <p className="text-muted-foreground">
                  If you have any questions about this disclaimer, please contact us at legal@kair0s.com
                </p>
              </section>

              <section>
                <p className="text-sm text-muted-foreground">
                  Last updated: {new Date().toLocaleDateString()}
                </p>
              </section>
            </div>
          </div>
        </Container>
      </div>
    </div>
  )
}
